#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HomeAutomationApp.Droid.Resource", IsApplication=true)]

namespace HomeAutomationApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Gcm.Client.Resource.String.library_name = global::HomeAutomationApp.Droid.Resource.String.library_name;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.error = global::HomeAutomationApp.Droid.Resource.Drawable.error;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.info = global::HomeAutomationApp.Droid.Resource.Drawable.info;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.success = global::HomeAutomationApp.Droid.Resource.Drawable.success;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.warning = global::HomeAutomationApp.Droid.Resource.Drawable.warning;
			global::Toasts.Forms.Plugin.Droid.Resource.Id.desc = global::HomeAutomationApp.Droid.Resource.Id.desc;
			global::Toasts.Forms.Plugin.Droid.Resource.Id.image = global::HomeAutomationApp.Droid.Resource.Id.image;
			global::Toasts.Forms.Plugin.Droid.Resource.Id.title = global::HomeAutomationApp.Droid.Resource.Id.title;
			global::Toasts.Forms.Plugin.Droid.Resource.Layout.crouton = global::HomeAutomationApp.Droid.Resource.Layout.crouton;
			global::Toasts.Forms.Plugin.Droid.Resource.String.ApplicationName = global::HomeAutomationApp.Droid.Resource.String.ApplicationName;
			global::Toasts.Forms.Plugin.Droid.Resource.String.Hello = global::HomeAutomationApp.Droid.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::HomeAutomationApp.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::HomeAutomationApp.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int error = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int info = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Mic = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int monoandroidsplash = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int success = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int warning = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int GCMRegister = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int GCMUnregister = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int desc = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int deviceID = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int image = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int linearLayout1 = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int micButton = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int myTextBox = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int notifyBtn = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int textView1 = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int title = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int crouton = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HomeLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int NotificationLayout = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
